// Code generated by internal/float.tmpl, DO NOT EDIT.

package ens

import (
	"reflect"
)

var _ Fielder = (*float64Builder)(nil)
var float64Type = reflect.TypeOf(float64(0))

// Float64 returns a new Field with type float64.
func Float64(name string) *float64Builder {
	return &float64Builder{
		&FieldDescriptor{
			Name: name,
			Type: Float64Type(),
		},
	}
}

// float64Builder is the builder for float64 fields.
type float64Builder struct {
	inner *FieldDescriptor
}

// Comment sets the comment of the field.
func (b *float64Builder) Comment(c string) *float64Builder {
	b.inner.Comment = c
	return b
}

// Nullable indicates that this field is a nullable.
func (b *float64Builder) Nullable() *float64Builder {
	b.inner.Nullable = true
	return b
}

// Definition set the sql definition of the field.
func (b *float64Builder) Definition(s string) *float64Builder {
	b.inner.Definition = s
	return b
}

// GoType overrides the default Go type with a custom one.
//
//	field.Float64("float64").
//		GoType(pkg.Float64(0))
func (b *float64Builder) GoType(typ any) *float64Builder {
	b.inner.goType(typ)
	return b
}

// Optional indicates that this field is optional.
// Unlike "Nullable" only fields,
// "Optional" fields are pointers in the generated struct.
func (b *float64Builder) Optional() *float64Builder {
	b.inner.Optional = true
	return b
}

// Tags adds a list of tags to the field tag.
//
//	field.Float64("float64").
//		Tags("yaml:"xxx"")
func (b *float64Builder) Tags(tags ...string) *float64Builder {
	b.inner.Tags = append(b.inner.Tags, tags...)
	return b
}

// Build implements the Fielder interface by returning its descriptor.
func (b *float64Builder) Build(opt *Option) *FieldDescriptor {
	//	b.inner.checkGoType(float64Type)
	b.inner.build(opt)
	return b.inner
}
