// Code generated by internal/integer.tpl, DO NOT EDIT.

package ens

import (
	"reflect"
)

var _ Fielder = (*uint32Builder)(nil)
var uint32Type = reflect.TypeOf(uint32(0))

// Uint32 returns a new Field with type uint32.
func Uint32(name string) *uint32Builder {
	return &uint32Builder{
		&FieldDescriptor{
			Name: name,
			Type: Uint32Type(),
		},
	}
}

// uint32Builder is the builder for uint32 field.
type uint32Builder struct {
	inner *FieldDescriptor
}

// Comment sets the comment of the field.
func (b *uint32Builder) Comment(c string) *uint32Builder {
	b.inner.Comment = c
	return b
}

// Nullable indicates that this field is a nullable.
func (b *uint32Builder) Nullable() *uint32Builder {
	b.inner.Nullable = true
	return b
}

// Definition set the sql definition of the field.
func (b *uint32Builder) Definition(s string) *uint32Builder {
	b.inner.Definition = s
	return b
}

// GoType overrides the default Go type with a custom one.
//
//	field.Uint32("uint32").
//		GoType(pkg.Uint32(0))
func (b *uint32Builder) GoType(typ any) *uint32Builder {
	b.inner.goType(typ)
	return b
}

// Optional indicates that this field is optional.
// Unlike "Nullable" only fields,
// "Optional" fields are pointers in the generated struct.
func (b *uint32Builder) Optional() *uint32Builder {
	b.inner.Optional = true
	return b
}

// Tags adds a list of tags to the field tag.
//
//	field.Uint32("uint32").
//		Tags("yaml:"xxx"")
func (b *uint32Builder) Tags(tags ...string) *uint32Builder {
	b.inner.Tags = append(b.inner.Tags, tags...)
	return b
}

// Build implements the Fielder interface by returning its descriptor.
func (b *uint32Builder) Build(opt *Option) *FieldDescriptor {
	//	b.inner.checkGoType(uint32Type)
	b.inner.build(opt)
	return b.inner
}
