// Code generated by internal/integer.tpl, DO NOT EDIT.

package ens

import (
	"reflect"
)

var _ Fielder = (*int32Builder)(nil)
var int32Type = reflect.TypeOf(int32(0))

// Int32 returns a new Field with type int32.
func Int32(name string) *int32Builder {
	return &int32Builder{
		&FieldDescriptor{
			Name: name,
			Type: Int32Type(),
		},
	}
}

// int32Builder is the builder for int32 field.
type int32Builder struct {
	inner *FieldDescriptor
}

// Comment sets the comment of the field.
func (b *int32Builder) Comment(c string) *int32Builder {
	b.inner.Comment = c
	return b
}

// Nullable indicates that this field is a nullable.
func (b *int32Builder) Nullable() *int32Builder {
	b.inner.Nullable = true
	return b
}

// Definition set the sql definition of the field.
func (b *int32Builder) Definition(s string) *int32Builder {
	b.inner.Definition = s
	return b
}

// GoType overrides the default Go type with a custom one.
//
//	field.Int32("int32").
//		GoType(pkg.Int32(0))
func (b *int32Builder) GoType(typ any) *int32Builder {
	b.inner.goType(typ)
	return b
}

// Optional indicates that this field is optional.
// Unlike "Nullable" only fields,
// "Optional" fields are pointers in the generated struct.
func (b *int32Builder) Optional() *int32Builder {
	b.inner.Optional = true
	return b
}

// Tags adds a list of tags to the field tag.
//
//	field.Int32("int32").
//		Tags("yaml:"xxx"")
func (b *int32Builder) Tags(tags ...string) *int32Builder {
	b.inner.Tags = append(b.inner.Tags, tags...)
	return b
}

// Build implements the Fielder interface by returning its descriptor.
func (b *int32Builder) Build(opt *Option) *FieldDescriptor {
	//	b.inner.checkGoType(int32Type)
	b.inner.build(opt)
	return b.inner
}
