// Code generated by internal/integer.tpl, DO NOT EDIT.

package ens

import (
	"reflect"
)

var _ Fielder = (*int16Builder)(nil)
var int16Type = reflect.TypeOf(int16(0))

// Int16 returns a new Field with type int16.
func Int16(name string) *int16Builder {
	return &int16Builder{
		&FieldDescriptor{
			Name: name,
			Type: Int16Type(),
		},
	}
}

// int16Builder is the builder for int16 field.
type int16Builder struct {
	inner *FieldDescriptor
}

// Comment sets the comment of the field.
func (b *int16Builder) Comment(c string) *int16Builder {
	b.inner.Comment = c
	return b
}

// Nullable indicates that this field is a nullable.
func (b *int16Builder) Nullable() *int16Builder {
	b.inner.Nullable = true
	return b
}

// GoType overrides the default Go type with a custom one.
//
//	field.Int16("int16").
//		GoType(pkg.Int16(0))
func (b *int16Builder) GoType(typ any) *int16Builder {
	b.inner.goType(typ)
	return b
}

// Optional indicates that this field is optional.
// Unlike "Nullable" only fields,
// "Optional" fields are pointers in the generated struct.
func (b *int16Builder) Optional() *int16Builder {
	b.inner.Optional = true
	return b
}

// Tags adds a list of tags to the field tag.
//
//	field.Int16("int16").
//		Tags("yaml:"xxx"")
func (b *int16Builder) Tags(tags ...string) *int16Builder {
	b.inner.Tags = append(b.inner.Tags, tags...)
	return b
}

// Build implements the Fielder interface by returning its descriptor.
func (b *int16Builder) Build(opt *Option) *FieldDescriptor {
	//	b.inner.checkGoType(int16Type)
	b.inner.build(opt)
	return b.inner
}
