// Code generated by internal/float.tmpl, DO NOT EDIT.

package ens

import (
	"reflect"
)

var _ Fielder = (*float32Builder)(nil)
var float32Type = reflect.TypeOf(float32(0))

// Float32 returns a new Field with type float32.
func Float32(name string) *float32Builder {
	return &float32Builder{
		&FieldDescriptor{
			Name: name,
			Type: Float32Type(),
		},
	}
}

// float32Builder is the builder for float32 fields.
type float32Builder struct {
	inner *FieldDescriptor
}

// Comment sets the comment of the field.
func (b *float32Builder) Comment(c string) *float32Builder {
	b.inner.Comment = c
	return b
}

// Nullable indicates that this field is a nullable.
func (b *float32Builder) Nullable() *float32Builder {
	b.inner.Nullable = true
	return b
}

// GoType overrides the default Go type with a custom one.
//
//	field.Float32("float32").
//		GoType(pkg.Float32(0))
func (b *float32Builder) GoType(typ any) *float32Builder {
	b.inner.goType(typ)
	return b
}

// Optional indicates that this field is optional.
// Unlike "Nullable" only fields,
// "Optional" fields are pointers in the generated struct.
func (b *float32Builder) Optional() *float32Builder {
	b.inner.Optional = true
	return b
}

// Tags adds a list of tags to the field tag.
//
//	field.Float32("float32").
//		Tags("yaml:"xxx"")
func (b *float32Builder) Tags(tags ...string) *float32Builder {
	b.inner.Tags = append(b.inner.Tags, tags...)
	return b
}

// Build implements the Fielder interface by returning its descriptor.
func (b *float32Builder) Build(opt *Option) *FieldDescriptor {
	//	b.inner.checkGoType(float32Type)
	b.inner.build(opt)
	return b.inner
}
