// Code generated by internal/integer.tpl, DO NOT EDIT.

package ens

import (
	"reflect"
)

var _ Fielder = (*int64Builder)(nil)
var int64Type = reflect.TypeOf(int64(0))

// Int64 returns a new Field with type int64.
func Int64(name string) *int64Builder {
	return &int64Builder{
		&FieldDescriptor{
			Name: name,
			Type: Int64Type(),
		},
	}
}

// int64Builder is the builder for int64 field.
type int64Builder struct {
	inner *FieldDescriptor
}

// Comment sets the comment of the field.
func (b *int64Builder) Comment(c string) *int64Builder {
	b.inner.Comment = c
	return b
}

// Nullable indicates that this field is a nullable.
func (b *int64Builder) Nullable() *int64Builder {
	b.inner.Nullable = true
	return b
}

// Definition set the sql definition of the field.
func (b *int64Builder) Definition(s string) *int64Builder {
	b.inner.Definition = s
	return b
}

// GoType overrides the default Go type with a custom one.
//
//	field.Int64("int64").
//		GoType(pkg.Int64(0))
func (b *int64Builder) GoType(typ any) *int64Builder {
	b.inner.goType(typ)
	return b
}

// Optional indicates that this field is optional.
// Unlike "Nullable" only fields,
// "Optional" fields are pointers in the generated struct.
func (b *int64Builder) Optional() *int64Builder {
	b.inner.Optional = true
	return b
}

// Tags adds a list of tags to the field tag.
//
//	field.Int64("int64").
//		Tags("yaml:"xxx"")
func (b *int64Builder) Tags(tags ...string) *int64Builder {
	b.inner.Tags = append(b.inner.Tags, tags...)
	return b
}

// Build implements the Fielder interface by returning its descriptor.
func (b *int64Builder) Build(opt *Option) *FieldDescriptor {
	//	b.inner.checkGoType(int64Type)
	b.inner.build(opt)
	return b.inner
}
