// Code generated by "stringer -type Type"; DO NOT EDIT.

package rapier

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Field-0]
	_ = x[Bool-1]
	_ = x[Int8-2]
	_ = x[Int16-3]
	_ = x[Int32-4]
	_ = x[Int64-5]
	_ = x[Int-6]
	_ = x[Uint8-7]
	_ = x[Uint16-8]
	_ = x[Uint32-9]
	_ = x[Uint64-10]
	_ = x[Uint-11]
	_ = x[Float32-12]
	_ = x[Float64-13]
	_ = x[String-14]
	_ = x[Decimal-15]
	_ = x[Bytes-16]
	_ = x[Time-17]
	_ = x[endType-18]
}

const _Type_name = "FieldBoolInt8Int16Int32Int64IntUint8Uint16Uint32Uint64UintFloat32Float64StringDecimalBytesTimeendType"

var _Type_index = [...]uint8{0, 5, 9, 13, 18, 23, 28, 31, 36, 42, 48, 54, 58, 65, 72, 78, 85, 90, 94, 101}

func (i Type) String() string {
	if i < 0 || i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
