package codegen

import (
	"strings"
)

func (g *CodeGen) GenDDL() *CodeGen {
	if !g.disableDocComment {
		g.Printf("-- Code generated by %s. DO NOT EDIT.\n", g.byName)
		g.Printf("-- version: %s\n", g.version)
		g.Println()
	}
	for _, et := range g.entities {
		if et.Table != nil {
			g.Printf("-- %s %s\n", et.Name, trimStructComment(et.Comment, "\n", "\n-- "))
			g.Printf("%s;\n", et.Table.Definition())
			g.Println()
		}
	}
	return g
}

func trimStructComment(s, old, new string) string {
	return strings.ReplaceAll(strings.TrimSpace(s), old, new)
}
