package codegen

import "strings"

func (g *CodeGen) GenDDL() *CodeGen {
	if !g.disableDocComment {
		g.P("-- Code generated by ", g.byName, ". DO NOT EDIT.")
		g.P("-- version: ", g.version)
		g.P()
	}
	for _, et := range g.entities {
		g.P("-- ", et.Name, " ", trimStructComment(et.Comment, "\n", "\n-- "))
		g.P(et.Definition)
		g.P()
	}
	return g
}

func trimStructComment(s, old, new string) string {
	return strings.ReplaceAll(strings.TrimSpace(s), old, new)
}
