package codegen

func (g *CodeGen) GenDDL() *CodeGen {
	g.P("-- Code generated by ", g.byName, ". DO NOT EDIT.")
	g.P("-- version: ", g.version)
	g.P()

	for _, md := range g.entities {
		g.P("-- ", md.Name, " ", md.Comment)
		g.P(md.Definition)
		g.P()
	}
	return g
}
